import { expect, test, type Page, type Locator } from '@playwright/test';
import type { WorkspaceState } from '../../contracts/domain';
const key = 'aramis.workspace.demo.v1';
async function state(page:Page):Promise<WorkspaceState> { return page.evaluate(key => JSON.parse(localStorage.getItem(key)!),key); }
async function openRequest(page:Page, dialog:Locator){
  const popupPromise = page.waitForEvent('popup');
  await dialog.getByRole('link',{name:'Abrir como cliente'}).click();
  const popup = await popupPromise;
  await popup.waitForLoadState();
  return popup;
}

test('recorrido del equipo: crear, recibir material, pedir cambios, aprobar y publicar una versión',async({page})=>{
  const errors:string[]=[]; page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button',{name:'Nuevo contenido'}).click();
  let dialog=page.getByRole('dialog');
  await dialog.getByLabel('Título del contenido').fill('Campaña de prueba completa');
  await dialog.getByLabel('Responsable').selectOption({label:'Mateo · demo'});
  await dialog.getByRole('button',{name:'Crear contenido'}).click();
  dialog=page.getByRole('dialog');
  await expect(dialog.getByRole('heading',{name:'Campaña de prueba completa'})).toBeVisible();
  await expect(dialog.getByText('No figura en el calendario del cliente')).toBeVisible();
  const pieceId=(await state(page)).pieces.find(piece=>piece.title==='Campaña de prueba completa')!.id;
  await dialog.getByRole('button',{name:'Empezar producción'}).click();
  await expect(dialog.locator('.status-pill')).toHaveText('En producción');
  await dialog.getByRole('tab',{name:'Material',exact:true}).click();
  await dialog.getByLabel('Instrucciones').fill('Dos tomas verticales del espacio.');
  await dialog.getByRole('button',{name:'Preparar pedido'}).click();
  await dialog.getByRole('button',{name:'Generar enlace de prueba'}).click();
  const material=await openRequest(page,dialog);
  await material.locator('input[type=file]').setInputFiles({name:'toma.mp4',mimeType:'video/mp4',buffer:Buffer.from('fixture local sin video')});
  await material.getByRole('button',{name:'Registrar archivo de prueba'}).click();
  await expect(dialog.getByText('Revisar lo recibido')).toBeVisible();
  await material.close();
  expect((await state(page)).pieces.find(piece=>piece.id===pieceId)?.ownerId).toBe('member-mateo');
  await dialog.getByRole('button',{name:'Confirmar material completo'}).click();
  await expect(dialog.getByText('Completado',{exact:true})).toBeVisible();
  await dialog.getByRole('tab',{name:'Revisión',exact:true}).click();
  await dialog.getByLabel('Texto que revisará el cliente').fill('Texto de la versión uno.');
  await dialog.getByRole('button',{name:'Preparar revisión de prueba'}).click();
  await dialog.getByRole('button',{name:'Generar enlace de prueba'}).click();
  await expect(dialog.getByText('Sin envío registrado')).toBeVisible();
  const review1=await openRequest(page,dialog);
  await expect(dialog.getByText('Sin envío registrado')).toBeVisible();
  await review1.getByRole('button',{name:'Pedir cambios',exact:true}).click();
  await review1.getByLabel('¿Qué te gustaría cambiar?').fill('Reemplazar el cierre del texto.');
  await review1.getByRole('button',{name:'Enviar cambios'}).click();
  await expect(dialog.getByText('Cambios pedidos',{exact:true})).toBeVisible();
  await dialog.getByRole('button',{name:'Preparar nueva versión'}).click();
  await dialog.getByLabel('Texto que revisará el cliente').fill('Texto de la versión dos, con cierre revisado.');
  await dialog.getByRole('button',{name:'Preparar revisión de prueba'}).click();
  await expect(dialog.getByRole('heading',{name:'Versión 2',exact:true})).toBeVisible();
  await review1.reload();
  await expect(review1.getByRole('heading',{name:'Este enlace no está disponible.'})).toBeVisible();
  await review1.close();
  await dialog.getByRole('button',{name:'Generar enlace de prueba'}).click();
  await dialog.getByRole('button',{name:'Marcar como enviado',exact:true}).click();
  await expect(dialog.getByText(/Envío registrado ·/)).toBeVisible();
  const review2=await openRequest(page,dialog);
  await expect(review2.getByText('Texto de la versión dos, con cierre revisado.')).toBeVisible();
  await review2.getByRole('button',{name:'Aprobar contenido'}).click();
  await expect(dialog.getByText('Aprobada',{exact:true})).toBeVisible();
  await review2.close();
  await dialog.getByRole('tab',{name:'Detalles',exact:true}).click();
  await dialog.getByRole('button',{name:'Marcar como programado'}).click();
  await expect(dialog.locator('.status-pill')).toHaveText('Programado');
  await dialog.getByRole('button',{name:'Marcar como publicado'}).click();
  await expect(dialog.locator('.status-pill')).toHaveText('Publicado');
  await expect(dialog.getByRole('textbox',{name:'Texto de publicación',exact:true})).toBeDisabled();
  await dialog.getByRole('tab',{name:'Revisión',exact:true}).click();
  await expect(dialog.getByRole('button',{name:'Preparar nueva versión'})).toHaveCount(0);
  const saved=await state(page);
  expect(saved.pieces.find(piece=>piece.id===pieceId)).toMatchObject({status:'published',ownerId:'member-mateo'});
  expect(saved.reviews.filter(review=>review.pieceId===pieceId).map(review=>[review.version,review.status])).toEqual([[1,'changes'],[2,'approved']]);
  expect(saved.materials.find(request=>request.pieceId===pieceId)?.status).toBe('complete');
  expect(errors).toEqual([]);
});

test('un formulario de revisión viejo no reemplaza una versión creada en otra pestaña',async({page,context})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'Abrir Tu rincón favorito'}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByRole('tab',{name:'Revisión',exact:true}).click();
  await dialog.getByRole('button',{name:'Preparar nueva versión'}).click();
  await dialog.getByLabel('Texto que revisará el cliente').fill('Borrador viejo que no debe reemplazar el nuevo');
  const second=await context.newPage();
  await second.goto('/');
  await second.getByRole('button',{name:'Abrir Tu rincón favorito'}).click();
  const other=second.getByRole('dialog');
  await other.getByRole('tab',{name:'Revisión',exact:true}).click();
  await other.getByRole('button',{name:'Preparar nueva versión'}).click();
  await other.getByLabel('Texto que revisará el cliente').fill('Versión vigente de la otra pestaña');
  await other.getByRole('button',{name:'Preparar revisión de prueba'}).click();
  await expect(dialog.getByText(/La pieza cambió desde que abriste esta revisión/)).toBeVisible();
  await expect(dialog.getByLabel('Texto que revisará el cliente')).toHaveValue('Borrador viejo que no debe reemplazar el nuevo');
  await dialog.getByRole('button',{name:'Preparar revisión de prueba'}).click();
  await expect(dialog.getByRole('alert')).toBeVisible();
  const saved=await state(page);
  expect(saved.reviews.filter(review=>review.pieceId==='piece-oliva-review')).toHaveLength(2);
  expect(saved.pieces.find(piece=>piece.id==='piece-oliva-review')?.caption).toBe('Versión vigente de la otra pestaña');
  await second.close();
});

test('una respuesta WhatsApp y un mensaje editado no se trasladan a otra revisión',async({page,context})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'Abrir Tu rincón favorito'}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByRole('tab',{name:'Revisión',exact:true}).click();
  await dialog.getByLabel('Mensaje de ejemplo').fill('Mensaje editado con el link viejo /request/demo-review');
  await dialog.getByRole('button',{name:/Registrar respuesta recibida por WhatsApp/}).click();
  await dialog.getByLabel('Nombre de quien respondió').fill('Contacto de la versión uno');
  await dialog.getByRole('combobox',{name:'Respuesta',exact:true}).selectOption('approved');
  const second=await context.newPage();
  await second.goto('/');
  await second.getByRole('button',{name:'Abrir Tu rincón favorito'}).click();
  const other=second.getByRole('dialog');
  await other.getByRole('tab',{name:'Revisión',exact:true}).click();
  await other.getByRole('button',{name:'Preparar nueva versión'}).click();
  await other.getByLabel('Texto que revisará el cliente').fill('Una versión dos distinta');
  await other.getByRole('button',{name:'Preparar revisión de prueba'}).click();
  await expect(dialog.getByRole('heading',{name:'Versión 2',exact:true})).toBeVisible();
  await expect(dialog.getByLabel('Nombre de quien respondió')).toHaveCount(0);
  await dialog.getByRole('button',{name:'Generar enlace de prueba'}).click();
  const href=await dialog.getByRole('link',{name:'Abrir como cliente'}).getAttribute('href');
  await expect(dialog.getByLabel('Mensaje de ejemplo')).toHaveValue(new RegExp(href!));
  await expect(dialog.getByLabel('Mensaje de ejemplo')).not.toHaveValue(/demo-review/);
  expect((await state(page)).pieces.find(piece=>piece.id==='piece-oliva-review')?.status).toBe('review');
  await second.close();
});

test('publicar requiere resolver los cambios sin guardar del editor',async({page})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'Abrir Ideas para compartir'}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByRole('textbox',{name:'Texto de publicación',exact:true}).fill('Texto modificado que todavía no está aprobado');
  await expect(dialog.getByRole('button',{name:'Marcar como publicado'})).toBeDisabled();
  await dialog.getByRole('tab',{name:'Revisión',exact:true}).click();
  await expect(dialog.getByRole('alert')).toContainText('Guardá los detalles');
  await expect(dialog.getByRole('textbox',{name:'Texto de publicación',exact:true})).toHaveValue('Texto modificado que todavía no está aprobado');
  await dialog.getByRole('button',{name:'Descartar borrador'}).click();
  await expect(dialog.getByRole('button',{name:'Marcar como publicado'})).toBeEnabled();
});

test('una edición de otra pestaña no pisa el borrador y el guardado persiste al recargar',async({page,context})=>{
  await page.goto('/');
  const trigger=page.getByRole('button',{name:'Abrir Tu rincón favorito'});
  await trigger.click();
  const dialog=page.getByRole('dialog');
  await dialog.getByLabel('Nota interna').fill('Borrador todavía sin guardar');
  const second=await context.newPage();
  await second.goto('/');
  await second.getByRole('button',{name:'Abrir Tu rincón favorito'}).click();
  await second.getByRole('dialog').getByLabel('Nota interna').fill('Cambio guardado desde otra pestaña');
  await second.getByRole('button',{name:'Guardar cambios'}).click();
  await expect(dialog.getByText(/La pieza cambió mientras la editabas/)).toBeVisible();
  await expect(dialog.getByLabel('Nota interna')).toHaveValue('Borrador todavía sin guardar');
  await dialog.getByRole('button',{name:'Guardar cambios'}).click();
  await expect(dialog.getByRole('alert')).toContainText('El contenido cambió');
  expect((await state(page)).pieces.find(piece=>piece.id==='piece-oliva-review')?.internalNote).toBe('Cambio guardado desde otra pestaña');
  await dialog.getByRole('button',{name:'Cargar datos actuales'}).click();
  await expect(dialog.getByLabel('Nota interna')).toHaveValue('Cambio guardado desde otra pestaña');
  await dialog.getByRole('button',{name:'Cerrar',exact:true}).click();
  await expect(trigger).toBeFocused();
  await page.reload();
  await page.getByRole('button',{name:'Abrir Tu rincón favorito'}).click();
  await expect(page.getByRole('dialog').getByLabel('Nota interna')).toHaveValue('Cambio guardado desde otra pestaña');
  await second.close();
});

test('los vencimientos de material lejanos aparecen esta semana y en móvil sigue visible el siguiente paso',async({page})=>{
  await page.goto('/');
  await page.evaluate(key=>{const snapshot=JSON.parse(localStorage.getItem(key)!);snapshot.pieces.find((p:{id:string})=>p.id==='piece-oliva-material').plannedDate='2099-01-01';localStorage.setItem(key,JSON.stringify(snapshot));},key);
  await page.reload();
  await expect(page.getByRole('button',{name:'Abrir Así se vive Casa Oliva'})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  const row=page.getByRole('button',{name:'Abrir Así se vive Casa Oliva'});
  await expect(row.getByText('Falta material')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.getByRole('button',{name:'Abrir menú'}).click();
  await page.getByRole('button',{name:'Clientes',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Nuestras marcas.'})).toBeVisible();
});
