import { expect,test,type Page } from '@playwright/test';
const key='aramis.workspace.demo.v1';
async function clients(page:Page){await page.getByRole('button',{name:'Clientes',exact:true}).click();}
async function openClient(page:Page,name:string){await clients(page);await page.locator('.brand-card').filter({has:page.getByRole('heading',{name,exact:true})}).getByRole('button',{name:'Trabajar mes'}).click();}

test('Miguel configura un cliente y su mes, Eliana toma la pieza desde producción',async({page})=>{
 await page.goto('/');await clients(page);await page.getByRole('button',{name:'Nuevo cliente'}).click();
 let dialog=page.getByRole('dialog');await dialog.getByLabel('Nombre del cliente').fill('Cliente de prueba mensual');await dialog.getByLabel('Contacto').fill('Contacto del equipo');await dialog.getByLabel('Posteos por mes').fill('2');await dialog.getByLabel('Reels por mes').fill('1');await dialog.getByRole('button',{name:'Crear cliente',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Cliente de prueba mensual',exact:true})).toBeVisible();
 await page.getByLabel('Mes de trabajo').fill('2099-10');await page.getByRole('button',{name:'Generar base del mes'}).click();await expect(page.locator('.monthly-row')).toHaveCount(3);await expect(page.getByRole('button',{name:'Base generada'})).toBeDisabled();
 const row=page.getByRole('form',{name:'Editar Reel 01',exact:true});await row.getByLabel('Título de Reel 01').fill('Congreso de octubre');await row.getByLabel('Fecha de Reel 01').fill('2099-10-15');await row.getByRole('button',{name:'Guardar',exact:true}).click();
 await page.getByRole('form',{name:'Editar Congreso de octubre'}).getByRole('button',{name:'Abrir',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Guion e instrucciones de producción').fill('Presentación, tres tomas y cierre.');await dialog.getByRole('button',{name:'Guardar cambios'}).click();await dialog.getByRole('button',{name:'Pasar a producción',exact:true}).click();await dialog.getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.getByRole('button',{name:'Producción',exact:true}).click();await page.getByLabel('Filtrar por área').selectOption('design');await page.getByRole('button',{name:'Para producción',exact:true}).click();await expect(page.getByRole('button',{name:'Abrir Congreso de octubre'})).toBeVisible();
 await page.getByRole('button',{name:'Abrir Congreso de octubre'}).click();await expect(page.getByLabel('Guion e instrucciones de producción')).toHaveValue('Presentación, tres tomas y cierre.');await page.getByRole('button',{name:'Esperando grabación',exact:true}).click();await page.getByRole('button',{name:'Cerrar',exact:true}).click();await expect(page.getByRole('button',{name:'Abrir Congreso de octubre'})).toHaveCount(0);
 await page.reload();await openClient(page,'Cliente de prueba mensual');await page.getByLabel('Mes de trabajo').fill('2099-10');await expect(page.locator('.monthly-row')).toHaveCount(3);await expect(page.getByLabel('Fecha de Congreso de octubre')).toHaveValue('2099-10-15');
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Quitar Posteo 01 del mes'}).click();await expect(page.locator('.monthly-row')).toHaveCount(2);await expect(page.getByRole('button',{name:'Base generada'})).toBeDisabled();
 await page.getByRole('button',{name:'Agregar pieza',exact:true}).click();await page.getByRole('button',{name:'Agregar al mes'}).click();await expect(page.getByRole('heading',{name:'Posteo sin título'})).toBeVisible();await page.getByRole('button',{name:'Cerrar',exact:true}).click();await expect(page.locator('.monthly-row')).toHaveCount(3);
 await page.getByRole('button',{name:'Esta semana',exact:false}).first().click();await expect(page.getByRole('button',{name:'Abrir Posteo sin título'})).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Abrir menú'}).click();await openClient(page,'Cliente de prueba mensual');await page.getByLabel('Mes de trabajo').fill('2099-10');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});

test('material del equipo conserva video, previsualización y descarga al recargar',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Abrir Detrás de cada proyecto'}).click();await page.getByRole('tab',{name:'Material',exact:true}).click();
 const bytes=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=64;canvas.height=64;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#8b2634';ctx.fillRect(0,0,64,64);const stream=canvas.captureStream(10);const recorder=new MediaRecorder(stream,{mimeType:'video/webm'});const parts:Blob[]=[];return await new Promise<number[]>(resolve=>{recorder.ondataavailable=e=>parts.push(e.data);recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());resolve(Array.from(new Uint8Array(await new Blob(parts).arrayBuffer())));};recorder.start();setTimeout(()=>recorder.stop(),300);});});
 await page.getByLabel('Agregar material del equipo').setInputFiles({name:'tomas-equipo.webm',mimeType:'video/webm',buffer:Buffer.from(bytes)});
 const asset=page.locator('.team-asset').filter({hasText:'tomas-equipo.webm'});await expect(asset.getByRole('link',{name:'Descargar'})).toBeVisible();await expect.poll(()=>asset.locator('video').evaluate((v:HTMLVideoElement)=>v.readyState)).toBeGreaterThanOrEqual(2);
 await page.reload();await page.getByRole('button',{name:'Abrir Detrás de cada proyecto'}).click();await page.getByRole('tab',{name:'Material',exact:true}).click();await expect(asset.getByRole('link',{name:'Descargar'})).toBeVisible();
 const downloadPromise=page.waitForEvent('download');await asset.getByRole('link',{name:'Descargar'}).click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe('tomas-equipo.webm');const stream=await download.createReadStream();const chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks)).toEqual(Buffer.from(bytes));
 const stored=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),key);const file=stored.pieces.find((p:{id:string})=>p.id==='piece-norte-production').teamAssets.find((a:{name:string})=>a.name==='tomas-equipo.webm');expect(file.url).toBeUndefined();expect(file.driveFileId).toBeUndefined();
});

test('edición mensual en dos pestañas conserva el borrador y exige resolver el conflicto',async({page,context})=>{
 await page.goto('/');await openClient(page,'Casa Oliva');const row=page.getByRole('form',{name:'Editar Tu rincón favorito'});await row.getByLabel('Título de Tu rincón favorito').fill('Borrador Miguel');
 const other=await context.newPage();await other.goto('/');await openClient(other,'Casa Oliva');const otherRow=other.getByRole('form',{name:'Editar Tu rincón favorito'});await otherRow.getByLabel('Título de Tu rincón favorito').fill('Cambio guardado');await otherRow.getByRole('button',{name:'Guardar',exact:true}).click();
 const current=page.getByRole('form',{name:'Editar Cambio guardado'});await expect(current.getByLabel('Título de Cambio guardado')).toHaveValue('Borrador Miguel');await current.getByRole('button',{name:'Guardar',exact:true}).click();await expect(current.getByRole('alert')).toContainText('El contenido cambió');await current.getByRole('button',{name:'Descartar y cargar datos actuales'}).click();await expect(current.getByLabel('Título de Cambio guardado')).toHaveValue('Cambio guardado');await other.close();
});
