import { useEffect, useState } from 'react';
import { Copy, ArrowLeft } from 'lucide-react';
import { FORMAT_LABELS } from '../../contracts/domain';
import { APP_MODE, useWorkspace } from '../lib/api';
import ClientAvatar from '../components/ClientAvatar';
import './piece-text.css';
export default function PieceText({pieceId}:{pieceId:string}){
 const {state,error}=useWorkspace();const [notice,setNotice]=useState('');const piece=state.pieces.find(item=>item.id===pieceId&&!item.archived);const client=piece&&state.clients.find(item=>item.id===piece.clientId);
 useEffect(()=>{document.title=piece?`${piece.title} · Texto · Aramis`:'Texto no disponible · Aramis';},[piece?.title]);
 if(!piece||!client)return <main className="piece-text-page"><h1>Esta pieza no está disponible</h1><p>Puede haberse archivado o no estar disponible en este espacio.</p><a className="button secondary" href="/">Volver al panel</a></main>;
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice('Texto copiado.');}catch{setNotice('No se pudo copiar. Podés seleccionar el texto y copiarlo manualmente.');}}
 return <div className="piece-text-shell"><header className="piece-text-toolbar"><a href="/" className="text-button"><ArrowLeft size={15}/>Panel</a><span>Sólo equipo · {APP_MODE === 'demo' ? 'Demostración local' : 'Espacio compartido'}</span></header><main className="piece-text-page"><div className="piece-text-client"><ClientAvatar client={client}/><div><strong>{client.name}</strong><span>{FORMAT_LABELS[piece.format]}{piece.plannedDate?` · ${new Intl.DateTimeFormat('es-AR',{day:'numeric',month:'long'}).format(new Date(piece.plannedDate+'T12:00:00'))}`:''}</span></div></div><h1>{piece.title}</h1><p className="piece-text-update">Vista de lectura · Se actualiza al guardar cambios en la pieza.</p>{error&&<p role="alert" className="error-banner">{error}</p>}{notice&&<p role="status" className="notice-banner">{notice}</p>}{piece.format==='story' ? <><TextSection title="Contenido de la historia" text={piece.caption} empty="Todavía no hay contenido guardado para esta historia." copy={copy}/>{!!piece.script?.trim()&&<TextSection title="Indicaciones anteriores · sólo equipo" text={piece.script} copy={copy}/>}</> : <><TextSection title={piece.format==='reel'?'Guion e instrucciones':'Texto por placas e instrucciones'} text={piece.script??''} empty="Todavía no hay guion ni instrucciones guardados." copy={copy}/><TextSection title="Texto de publicación" text={piece.caption} empty="Todavía no hay texto de publicación guardado." copy={copy}/></>}{piece.internalNote&&<TextSection title="Notas para el equipo" text={piece.internalNote} copy={copy}/>}</main></div>;
}
function TextSection({title,text,empty,copy}:{title:string;text:string;empty?:string;copy:(text:string)=>void}){return <section className="piece-text-section"><div><h2>{title}</h2>{text&&<button className="text-button" onClick={()=>copy(text)} aria-label={`Copiar ${title.toLowerCase()}`}><Copy size={15}/>Copiar</button>}</div>{text?<p className="piece-text-content">{text}</p>:<p className="piece-text-empty">{empty}</p>}</section>;}
