import { useMemo, useState, type FormEvent } from 'react';
import { ArrowDownToLine, ArrowRight, CalendarDays, Check, CheckCheck, ChevronLeft, ChevronRight, CircleHelp, Clock3, ExternalLink, Eye, Filter, LayoutDashboard, Menu, Plus, Search, Settings2, Users, X } from 'lucide-react';
import type { Command, ContentFormat, Piece, WorkspaceState } from '../../contracts/domain';
import { FORMAT_LABELS } from '../../contracts/domain';
import { addDays, localDate, piecePriority } from '../domain/selectors';
import { resetDemo, useWorkspace } from '../lib/api';
import { Empty, Modal, Status } from '../components/ui';
import PieceDetail from './PieceDetail';

type Page = 'week' | 'calendar' | 'clients' | 'settings';
type FilterKind = 'all' | 'attention' | 'review' | 'ready';
export function dateLabel(value: string | null, options: Intl.DateTimeFormatOptions = { day: 'numeric', month: 'short' }) { return value ? new Intl.DateTimeFormat('es-AR', options).format(new Date(`${value}T12:00:00`)) : 'Sin fecha'; }
export function nextAction(state: WorkspaceState, piece: Piece, today: string) {
  const material = state.materials.find(request => request.pieceId === piece.id && request.status !== 'complete');
  if (material?.status === 'received') return { text: 'Revisar material recibido', who: 'Equipo', urgent: true };
  if (material) return { text: 'Falta material', who: 'Cliente', urgent: !!material.dueDate && material.dueDate < today };
  if (piece.status === 'review') return { text: 'Esperando aprobación', who: 'Cliente', urgent: !!piece.plannedDate && piece.plannedDate < today };
  if (piece.status === 'approved') return { text: 'Listo para programar', who: 'Equipo', urgent: false };
  if (piece.status === 'scheduled') return { text: 'Confirmar publicación', who: 'Equipo', urgent: false };
  if (piece.status === 'published') return { text: 'Publicado', who: 'Listo', urgent: false };
  return { text: piece.status === 'planned' ? 'Empezar producción' : 'Continuar producción', who: 'Equipo', urgent: !!piece.plannedDate && piece.plannedDate < today };
}
export default function Workspace() {
  const { state, execute, error } = useWorkspace();
  const [page, setPage] = useState<Page>('week');
  const [filter, setFilter] = useState<FilterKind>('all');
  const [clientId, setClientId] = useState('all');
  const [ownerId, setOwnerId] = useState('all');
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [month, setMonth] = useState(() => localDate().slice(0, 7));
  const [notice, setNotice] = useState('');
  const today = localDate();
  const horizon = addDays(today, 7);
  const pieces = state.pieces.filter(piece => !piece.archived);
  const attention = pieces.filter(piece => nextAction(state, piece, today).urgent);
  const waiting = pieces.filter(piece => piece.status === 'review');
  const ready = pieces.filter(piece => ['approved', 'scheduled'].includes(piece.status));
  const filtered = pieces.filter(piece => (clientId === 'all' || piece.clientId === clientId) && (ownerId === 'all' || piece.ownerId === ownerId) && `${piece.title} ${state.clients.find(client => client.id === piece.clientId)?.name}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || filter === 'attention' && attention.includes(piece) || filter === 'review' && waiting.includes(piece) || filter === 'ready' && ready.includes(piece)));
  const shown = [...filtered].filter(piece => page !== 'week' || piece.status !== 'published' && (!piece.plannedDate || piece.plannedDate <= horizon)).sort((a, b) => piecePriority(state, a, today) - piecePriority(state, b, today) || (a.plannedDate ?? '9999').localeCompare(b.plannedDate ?? '9999'));
  const selectedPiece = pieces.find(piece => piece.id === selected);
  function act(command: Command) { try { return execute(command); } catch { return undefined; } }
  function navigate(next: Page) { setPage(next); setFilter('all'); setSearch(''); setClientId('all'); setOwnerId('all'); setMobileNav(false); setNotice(''); }
  function calendarLink(id: string) {
    const existing = state.shares.find(share => share.scope === 'calendar' && share.targetId === id && !share.revokedAt);
    if (existing) return `/calendar/${existing.token}`;
    const result = act({ type: 'create-share', scope: 'calendar', targetId: id });
    const created = result?.state.shares.find(share => share.id === result.entityId);
    return created ? `/calendar/${created.token}` : null;
  }
  function viewCalendar(id: string) { const href = calendarLink(id); if (href) location.href = href; }
  return <div className="workspace">
    {mobileNav && <button className="sidebar-backdrop" aria-label="Cerrar menú" onClick={() => setMobileNav(false)} />}
    <aside className={`sidebar ${mobileNav ? 'mobile-open' : ''}`}><a href="/" className="brand-word">aramís<span>.</span></a><div className="sidebar-caption">ESPACIO DE CONTENIDO</div><div className="workspace-badge"><span className="workspace-avatar">a</span><div><strong>Equipo Aramís</strong><small>Estudio creativo</small></div><Check size={14} /></div><div className="nav-caption">ORGANIZACIÓN</div><nav aria-label="Principal">{([{ id: 'week', label: 'Esta semana', icon: LayoutDashboard }, { id: 'calendar', label: 'Calendario', icon: CalendarDays }, { id: 'clients', label: 'Clientes', icon: Users }] as const).map(item => <button key={item.id} aria-current={page === item.id ? 'page' : undefined} className={page === item.id ? 'active' : ''} onClick={() => navigate(item.id)}><item.icon size={18} /><span>{item.label}</span>{item.id === 'week' && attention.length > 0 && <b>{attention.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><span className="sidebar-note-dot" /><strong>Cada pieza, un siguiente paso.</strong><p>Una vista compartida para que el trabajo siga.</p></div><button className={`sidebar-settings ${page === 'settings' ? 'active' : ''}`} onClick={() => navigate('settings')}><Settings2 size={18} />Configuración</button><div className="sidebar-person"><span>EA</span><div><strong>Equipo Aramís</strong><small>Vista de demostración</small></div></div></div></aside>
    <div className="workspace-body"><div className="demo-banner"><span><i />Demostración local · datos ficticios guardados en este navegador</span><button onClick={() => navigate('settings')}>Qué puedo probar <ArrowRight size={13} /></button></div><header className="topbar"><div><button className="icon-button mobile-menu" aria-label="Abrir menú" onClick={() => setMobileNav(true)}><Menu size={21} /></button><span>Aramís</span><span className="breadcrumb-slash">/</span><strong>{({week:'Esta semana',calendar:'Calendario',clients:'Clientes',settings:'Configuración'})[page]}</strong></div><span className="topbar-date"><CalendarDays size={15} />{dateLabel(today, { weekday: 'long', day: 'numeric', month: 'long' })}</span><button className="icon-button" aria-label="Ayuda sobre la demostración" onClick={() => navigate('settings')}><CircleHelp size={19} /></button></header>
    <main className="main-content">
      <div className="page-heading"><div><p className="eyebrow">{page === 'week' ? 'TODO EN SU LUGAR' : page === 'clients' ? 'UNA MIRADA POR MARCA' : page === 'settings' ? 'PRIMERA VERSIÓN · LOCAL' : 'DARLE LUGAR A CADA IDEA'}</p><h1>{({week:'Hagamos que avance.',calendar:'El contenido, en el tiempo.',clients:'Nuestras marcas.',settings:'Un espacio para probar.'})[page]}</h1><p>{({week:'Lo que necesita atención y lo que viene en los próximos 7 días.',calendar:'Fechas previstas de todas las marcas. Cada pieza conserva su responsable.',clients:'Abrí el calendario tal como lo ve cada cliente.',settings:'Probá los recorridos antes de conectar los servicios reales.'})[page]}</p></div>{page !== 'settings' && <button className="button primary" onClick={() => setCreating(true)}><Plus size={18} />Nuevo contenido</button>}</div>
      {error && <div className="error-banner" role="alert">{error}</div>}{notice && <div className="notice-banner" role="status">{notice}</div>}
      {page === 'week' && <><div className="stats-grid">{[{id:'attention' as const,count:attention.length,label:'Necesitan atención',note:'Resolver para seguir',icon:Clock3,color:'burgundy'},{id:'review' as const,count:waiting.length,label:'Esperan aprobación',note:'El siguiente paso es del cliente',icon:Eye,color:'blue'},{id:'ready' as const,count:ready.length,label:'Listos para salir',note:'Aprobados o programados',icon:CheckCheck,color:'green'}].map(stat => <button key={stat.id} className={`stat-card ${stat.color} ${filter === stat.id ? 'selected' : ''}`} aria-pressed={filter === stat.id} onClick={() => setFilter(filter === stat.id ? 'all' : stat.id)}><span className="stat-top"><span>{stat.label}</span><stat.icon size={19} /></span><strong>{String(stat.count).padStart(2,'0')}</strong><span className="stat-bottom">{stat.note}<ArrowRight size={15} /></span></button>)}</div><div className="section-heading"><div><h2>La mesa de trabajo <span>{shown.length}</span></h2><p>Primero lo urgente. Después, el próximo paso.</p></div>{filter !== 'all' && <button className="text-button" onClick={() => setFilter('all')}>Quitar filtro <X size={14} /></button>}</div></>}
      {(page === 'week' || page === 'calendar') && <><div className="filters"><label className="search-box"><Search size={17} /><input aria-label="Buscar contenido" placeholder="Buscar contenido o cliente…" value={search} onChange={event => setSearch(event.target.value)} /></label><div className="filter-select"><Filter size={15} /><select aria-label="Filtrar por cliente" value={clientId} onChange={event => setClientId(event.target.value)}><option value="all">Todos los clientes</option>{state.clients.map(client => <option value={client.id} key={client.id}>{client.name}</option>)}</select></div><select aria-label="Filtrar por responsable" value={ownerId} onChange={event => setOwnerId(event.target.value)}><option value="all">Todo el equipo</option>{state.members.map(member => <option value={member.id} key={member.id}>{member.name}</option>)}</select></div>{page === 'week' ? <div className="work-table"><div className="work-table-head"><span>CONTENIDO</span><span>FECHA PREVISTA</span><span>ESTADO</span><span>PRÓXIMO PASO</span><span /></div>{shown.length ? shown.map(piece => { const client = state.clients.find(client => client.id === piece.clientId)!; const owner = state.members.find(member => member.id === piece.ownerId)!; const next = nextAction(state, piece, today); const overdue = piece.plannedDate && piece.plannedDate < today; return <button className="work-row" key={piece.id} onClick={() => setSelected(piece.id)} aria-label={`Abrir ${piece.title}`}><div className="piece-cell"><span className="client-avatar" style={{background:`${client.color}15`,color:client.color}}>{client.initials}</span><div><span className="piece-client">{client.name} <b>·</b> {FORMAT_LABELS[piece.format]}</span><strong>{piece.title}</strong><span className="piece-owner"><i>{owner.initials}</i>{owner.name.replace(' · demo','')}{!piece.visibleToClient && <small>Interno</small>}</span></div></div><span className={`date-cell ${overdue ? 'overdue' : ''}`}>{dateLabel(piece.plannedDate)}{overdue && <small>Fecha vencida</small>}{!piece.plannedDate && <small>A definir</small>}</span><Status status={piece.status} /><span className={`next-cell ${next.urgent ? 'urgent' : ''}`}><span>{next.text}</span><small>{next.who}</small></span><ChevronRight size={17} /></button>; }) : <Empty><CheckCheck size={30} /><h3>Todo despejado por acá.</h3><p>Probá con otro filtro o creá una nueva pieza.</p></Empty>}<div className="table-footer"><span><span className="legend-dot" />Incluye vencidos y contenido sin fecha</span><span>{dateLabel(today)} — {dateLabel(horizon)}</span></div></div> : <InternalCalendar pieces={shown} state={state} month={month} setMonth={setMonth} select={setSelected} today={today} />}</>}
      {page === 'clients' && <div className="clients-grid">{state.clients.map(client => { const own = pieces.filter(piece => piece.clientId === client.id); const share = state.shares.find(item => item.scope === 'calendar' && item.targetId === client.id && !item.revokedAt); return <section className="brand-card" key={client.id}><span className="client-avatar large" style={{color:client.color,background:`${client.color}16`}}>{client.initials}</span><h2>{client.name}</h2><p>{own.filter(piece=>piece.visibleToClient).length} piezas visibles · {own.filter(piece=>piece.status === 'review').length} por aprobar</p><button className="button secondary" onClick={() => viewCalendar(client.id)}>Ver calendario del cliente <ExternalLink size={15} /></button>{share && <button className="text-button revoke-link" onClick={() => { if (confirm(`¿Revocar el enlace de calendario de ${client.name}? Dejará de abrir hasta que generes uno nuevo.`)) { act({type:'revoke-share',shareId:share.id}); setNotice('Enlace revocado. Al abrir el calendario se generará uno nuevo.'); } }}>Revocar enlace actual</button>}</section>; })}</div>}
      {page === 'settings' && <div className="settings-grid"><section className="settings-card"><span className="eyebrow">LISTO PARA RECORRER</span><h2>El trabajo de una semana.</h2><p>Creá contenido, asigná un responsable, pedí material y prepará una revisión. Abrí el enlace del cliente para responder y volvé al panel para ver el resultado.</p><ul><li>Calendario de cada cliente, en agenda y mes.</li><li>Aprobaciones vinculadas a una versión de texto y archivos.</li><li>Material recibido pendiente de control del equipo.</li><li>Mensajes preparados para copiar, con envío manual.</li></ul><a href="/calendar/demo-calendar" className="button secondary">Probar calendario de Casa Oliva <ArrowRight size={16} /></a></section><section className="settings-card"><span className="eyebrow">ALCANCE DE ESTA DEMO</span><h2>Todo queda en este navegador.</h2><p>Las modificaciones se conservan al recargar. Estos enlaces sólo funcionan con los mismos datos locales; todavía no se pueden compartir con clientes reales.</p><p>Los archivos seleccionados se simulan por nombre y tamaño: no se suben a Drive ni se conserva su contenido. El acceso real, el correo y la sincronización entre dispositivos requieren conectar los servicios.</p><div className="settings-actions"><button className="button secondary" onClick={() => { const link=document.createElement('a'); const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));link.href=url;link.download='aramis-demo.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Se descargó una copia de los datos ficticios de esta demostración.'); }}><ArrowDownToLine size={15} />Exportar datos de ejemplo</button><button className="text-button" onClick={() => { if (confirm('¿Restablecer la demostración? Se eliminarán los cambios locales y volverán los datos de ejemplo.')) {resetDemo();setNotice('Demostración restablecida.');} }}>Restablecer demostración</button></div></section></div>}
      <footer className="internal-footer"><span>Un poco de orden. Más espacio para crear.</span><span>aramís · contenido con intención</span></footer>
    </main></div>
    <Modal open={creating} onClose={() => setCreating(false)} title="Una nueva idea." description="Empezá por lo esencial. Los detalles vienen después."><CreatePiece state={state} onCreate={command => { const result=act(command); if(result){setCreating(false);setSelected(result.entityId);} }} /></Modal>
    {selectedPiece && <PieceDetail key={selectedPiece.id} piece={selectedPiece} state={state} execute={execute} onClose={() => setSelected(null)} />}
  </div>;
}
function CreatePiece({state,onCreate}:{state:WorkspaceState;onCreate:(command:Command)=>void}) {
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);onCreate({type:'create-piece',input:{title:String(values.get('title')),clientId:String(values.get('clientId')),ownerId:String(values.get('ownerId')),format:values.get('format') as ContentFormat,plannedDate:String(values.get('date'))||null}});}
  return <form className="form-stack" onSubmit={submit}><label>Título del contenido<input name="title" placeholder="Ej. Una presentación del equipo" required maxLength={200} autoFocus /></label><div className="form-columns"><label>Cliente<select name="clientId">{state.clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Responsable<select name="ownerId">{state.members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label>Formato<select name="format">{Object.entries(FORMAT_LABELS).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label>Fecha prevista<input name="date" type="date" /></label></div><p className="form-hint">Empieza como contenido interno. Vos elegís cuándo hacerlo visible al cliente.</p><button className="button primary" type="submit"><Plus size={16} />Crear contenido</button></form>;
}
function InternalCalendar({pieces,state,month,setMonth,select,today}:{pieces:Piece[];state:WorkspaceState;month:string;setMonth:(month:string)=>void;select:(id:string)=>void;today:string}){
  const days=useMemo(()=>{const first=new Date(`${month}-01T12:00:00`);first.setDate(first.getDate()-(first.getDay()+6)%7);return Array.from({length:42},(_,i)=>{const day=new Date(first);day.setDate(day.getDate()+i);return localDate(day);});},[month]);
  function move(step:number){const date=new Date(`${month}-01T12:00:00`);date.setMonth(date.getMonth()+step);setMonth(localDate(date).slice(0,7));}
  return <section className="internal-calendar"><div className="calendar-controls"><h2>{dateLabel(`${month}-01`,{month:'long',year:'numeric'})}</h2><div><button className="text-button" onClick={()=>setMonth(today.slice(0,7))}>Hoy</button><button className="icon-button" aria-label="Mes anterior" onClick={()=>move(-1)}><ChevronLeft size={18}/></button><button className="icon-button" aria-label="Mes siguiente" onClick={()=>move(1)}><ChevronRight size={18}/></button></div></div><div className="calendar-scroll"><div className="internal-weekdays">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(day=><span key={day}>{day}</span>)}</div><div className="internal-month-grid">{days.map(day=><div className={`internal-day ${day.slice(0,7)!==month?'outside':''} ${day===today?'today':''}`} key={day}><span>{Number(day.slice(-2))}</span>{pieces.filter(piece=>piece.plannedDate===day).map(piece=><button onClick={()=>select(piece.id)} key={piece.id}><i style={{background:state.clients.find(client=>client.id===piece.clientId)?.color}}/><strong>{piece.title}</strong><small>{state.clients.find(client=>client.id===piece.clientId)?.name}</small></button>)}</div>)}</div></div>{pieces.some(piece=>!piece.plannedDate)&&<div className="undated-list"><h3>Sin fecha</h3>{pieces.filter(piece=>!piece.plannedDate).map(piece=><button className="button secondary" key={piece.id} onClick={()=>select(piece.id)}>{piece.title}<ArrowRight size={14}/></button>)}</div>}</section>;
}
